version : '3.8'

services :

  postgres :
    image : postgres:15
    container_name : netflix_postgres
    restart : always
    environment : 
      POSTGRES_USER : netflix
      POSTGRES_PASSWORD : netflix
      POSTGRES_DB : netflix
    ports :
      - "5432:5432"
    volumes :
      - postgres_data:/var/lib/postgresql/data

  redis :
    image : redis:7
    container_name : netflix_redis
    ports :
      - "6379:6379"

  minio :
    image : minio/minio
    container_name : netflix_minio
    command : server /data --console-address ":9001"
    environment : 
      MINIO_ROOT_USER : admin
      MINIO_ROOT_PASSWORD : password123
    ports :
      - "9000:9000"
      - "9001:9001"
    volumes :
      - minio_data:/data

  api :
    build: ../services/api-gateway
    container_name : netflix_api
    ports :
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://netflix:netflix@postgres:5432/netflix
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-change-me
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on :
      - postgres
      - redis
      - minio
  
  worker :
    build : ../worker/transcoder
    container_name : netflix_worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - OUTPUT_BUCKET=videos
    depends_on :
      - redis
      - minio
    
volumes :
  postgres_data :
  minio_data :
